name: bitwarden_backup_decryptor
description: CLI tool to decrypt backup files exported from Bitwarden
version: 0.0.1
repository: https://github.com/elliotwutingfeng/bitwarden_backup_decryptor
funding:
  - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - encryption
  - security

publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  convert: ^3.1.2
  hashlib: ^2.3.0
  pointycastle: ^4.0.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.28.0
